@startuml
title RBAC-0 基础模型
'隐藏Entity标识
hide circle

'entity user <<泛型>>
entity "<<用户>>\nUser" as user {
}

entity " <<角色>> \nRole" as role {
}

entity " <<许可>> \nPermission" as perm {
  *<<操作>> ops
  *<<对象>> obs
}

entity " <<会话>> \nSession" as session {
}

user }o-right-o{role:"      "
role }o-right-o{perm:"     "
user ||--|| session
role }--|| session

newpage

title RBAC-1 分层模型
hide circle
'skinparam linetype ortho
entity " <<用户>> \nUser" as user {
}

entity " <<角色>> \nRole" as role {
}

entity " <<许可>> \nPermission" as perm {
* <<操作>> ops
* <<对象>> obs
}

entity " <<会话>> \nSession" as session {
}

user }o-right-o{role:"      "
role }o-right-o{perm:"     "
user ||--|| session
role }--|| session
role ||--o role
note bottom of role
在RBAC0模型之上引入了 **继承关系**，形
成了**角色分层模型**，继承分为**一般继承**
和**受限继承**
end note

newpage

title RBAC-2 约束模型
'隐藏Entity标识
hide circle

'entity user <<泛型>>
entity " <<用户>> \nUser" as user {
}

entity " <<角色>> \nRole" as role {
}

entity " <<许可>> \nPermission" as perm {
  *<<操作>> ops
  *<<对象>> obs
}

entity " <<会话>> \nSession" as session {
}

entity " <<静态职责分离>> \nSSD" as ssd #70d4ff {
}

entity " <<动态职责分离>> \nDSD" as dsd #fd953b {
}

note right of ssd
1. 互斥角色: 同一用户不能授予互斥角色，
    如：会计与审计角色互斥。
2. 基数约束: 一个用户对于的角色数受限或
    一个角色对应的用户数受限。
3. 先决条件约束: 用户想拥有 A 角色就必须
    先拥有 B 角色。
end note
note right of dsd
用户登录系统后动态
决定用户的角色
end note

ssd -- user
ssd -- role
user }o-right-o{role:"           "
role }o-right-o{perm:"          "
user ||--|| session
role }--|| session
dsd -up- role
dsd -left- session:"                      "


newpage

title RBAC-3 组合模型
'隐藏Entity标识
hide circle

'entity user <<泛型>>
entity " <<用户>> \nUser" as user {
}

entity " <<角色>> \nRole" as role {
}

entity " <<许可>> \nPermission" as perm {
  *<<操作>> ops
  *<<对象>> obs
}

entity " <<会话>> \nSession" as session {
}

entity " <<静态职责分离>> \nSSD" as ssd #70d4ff {
}

entity " <<动态职责分离>> \nDSD" as dsd #fd953b {
}

ssd -- user
ssd -- role
user }o-right-o{role:"           "
role }o-right-o{perm:"          "
user ||--|| session
role }--|| session
role ||--o role
dsd -up- role
dsd -left- session:"                      "
@enduml

