@startuml
newpage

title:系统用例

:参与者1: as act1
skinparam actorStyle awesome
actor "参与者2" as act2
skinparam actorStyle hollow
actor "参与者3" as act3
skinparam actorStyle matches
actor "参与者4" as act4

(用例1) as uc1
usecase (用例1) as uc1
usecase (用例1) as uc2
(用例3) as uc3 << 构造类型 >>

usecase ucd as "
**用例描述**

1. 使用换行
来分割描述用例
--
2. 使用双横线（减号）分割
==
3. 使用双等号来分割
..虚线..
4.使用虚线（双点）来分割
__
5. 使用下划线来分割
"

act1 --> uc1:**用例关系**
act2 --> uc2
act3 --> uc3
act4 --> ucd


newpage

title:业务用例
'left to right direction
actor/ "业务用户" as user
usecase/ (业务用例) as uc
user --> uc

note as xxx
* 业务用例：业务用例体现了需求，比如论坛
管理员(护用户,维护帖子等)。
* 系统用例: 系统用例只针对要开发的系统，
作为一个配合者
..
* 业务用例的执行者一般是人或组织，例如广
告客户、网民、市政机关、教委、图书馆；
* 系统用例的执行者为实际与系统交互的操作
人员或程序（外部衔接系统、自动服务、定时器）
end note

newpage

title 项目示例

left to right direction
actor "学生" as student
actor "老师" as teacher

usecase "修改成绩" as mod
usecase "查询成绩" as query
usecase "登录系统" as login

teacher -up-> mod
teacher -up-> query
teacher -up-> login
student --> query
student --> login

@enduml
