@startuml ad-full
title GBPC-完整应用模型

entity "**执行者**" as executor {
  *执行者ID  <PK>
  执行者名
}

entity "**分组**" as grouper {
  *分组ID  <PK>
  分组名
}

entity "**策略**" as policy {
  *策略ID  <PK>
  策略类型
}

entity "策略项" as item #fede35 {
  *操作ID  <PK>
  策略内容
}

entity "执行者组" as executorgroup #fede35 {
  *执行者组ID  <PK>
  执行者组名
}
note right of executorgroup
如:部门、公司
或关联分组等
end note


entity "执行者组-分组关联" as exgs #99FF99 {
  *执行者组ID <FK>
  *分组ID <FK>
}


entity "执行者组-执行者关联" as egex #99FF99 {
  *执行者组ID <FK>
  *执行者ID <FK>
}

entity "执行者-分组关联" as executor_grouper #99FF99 {
  *执行者ID <FK>
  *分组ID <FK>
}

entity "分组-策略关联" as grouper_policy #99FF99 {
  *分组ID <FK>
  *策略ID <FK>
}

entity "<<策略控制>>" as policy_contrl #70d4ff {
}

note bottom of policy_contrl
包括执行者与特殊策略，
条件约束表，互斥规则
等，可根据业务需要进
行扩展。
end note

entity "策略项关联" as item_policy #99FF99 {
  *策略ID <FK>
  *操作项ID <FK>
}

grouper_policy -up-> grouper

grouper_policy -up-> policy

executor_grouper -up-> executor
executor_grouper -up-> grouper

policy_contrl -left-> executor
policy_contrl -left-> policy
policy_contrl -left-> grouper

item_policy --> policy
item_policy -up-> item:业务扩展

egex --> executor
egex -up-> executorgroup

exgs --> grouper
exgs -up->executorgroup
@enduml