@startuml

|#99FF99|旅客|
start
:提交个人信息;
if (入住方式?) is (直接入住) then
  :**入住**;
  |服务员|
     #yellow:**办理入住手续**;
  |旅客|
    :住宿;
    :退房;
  |服务员|
     :办理退房手续;
else (预定)
  |服务员|
  #pink : **预定房间** ;
  |旅客|
    :提交订金;
  |服务员|
    : 登记入住信息;
 if (是否入住) is (是) then
   |旅客|
   :住宿;
 else

 endif
'  :foo2;

endif
stop

@enduml
