@startuml GBPC2
title GBPC-2 约束模型
'隐藏Entity标识
hide circle

'entity executer <<泛型>>
entity " <<执行者>> \nExecuter" as executer {
}

entity " <<分组>> \nGroup" as group {
}

entity " <<策略>> \nPolicy" as policy {
  *<<元数据>> meta
  *<<操作>> ops
}

entity " <<会话>> \nSession" as session {}

entity " <<静态职责分离>> \nSSD" as ssd #70d4ff {}

entity " <<动态职责分离>> \nDSD" as dsd #fd953b {}

note right of ssd
1. 互斥分组: 同一执行者不能授予互斥分组；
2. 基数约束: 执行者数、分组数和策略数相互制约；
3. 先决条件约束: 策略组A的执行依赖于策略组B；
end note
note right of dsd
终端与域账号、终端与硬件环境等动态制约
end note

ssd -- executer
ssd -- group
executer }o-right-o{group:"           "
group }o-right-o{policy:"          "
executer ||--|| session
group }--|| session
dsd -up- group
dsd -left- session:"                      "
@enduml

